config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  #create custom paths. i.e. user enters /signup, it redirects to users#new
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/ourStory', to: 'static_pages#about'
  get '/clubEvents', to: 'static_pages#events'
  get '/whoarewe', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #adding app resources
  #Users table(id,name,email,password_digest)
  #Converts to a RESTful resource
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  #before_save {email.downcase!} this will apply immediate effects to email using bang.
  before_save {self.email = email.downcase}
  validates(:name, presence: true, length: {maximum: 50})
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness:
  {case_sensitive: false})
  #rails : on uniqueness, rails just infers that uniqueness = true

  has_secure_password
  #this has a allow_nil for blank passwords, strictj
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  #Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home
  end

  def help
  end

  def about
  end

  def contacts
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    #@users = User.all
  end

  #this is public for all users
  def show
    #really a string "id" but rails converts to integer
    @user = User.find(params[:id])
    #Note: this @user could be removed bc/ we assign the variable when we call
    #correct_user, leaving for now (extra database call frowned reduction)

    #using the byebug which shows (byebug in server window)
    #debugger
  end

  def new
    @user = User.new
  end

  def create
    #note we can access :user because of the hash that is made
    #when converting rails code into html form information
    @user = User.new(user_params)
    if @user.save
      log_in @user   #log in via method in sessions controller helper.rb
      #if successfull, display on next page
      flash[:success] = "Welcome to OVSAC!"
      redirect_to(user_url(@user))
    else
      render('new')
    end
  end

  def edit
    #Note: this @user could be removed bc/ we assign the variable when we call
    #correct_user, leaving for now (extra database call frowned reduction)
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      #Handle a successful update
      flash[:success] = "Profile updated"
      redirect_to(@user)
    else
      render 'edit.html.erb'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  #indentation is simply for shoing these methods are inside private.
  private
    #use strong parameters to prevent mass assignment vulnerablity
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation,:ucid)
    end

    #Before filters
    def logged_in_user
      unless logged_in?    #note: method in session_controlelr helper
        store_location   #This stores the current page location on site, if login fails
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    #Filter: Confirms a correct user.
    def correct_user
      @user = User.find(params[:id])    #Note current_user defined in session_helper
      #redirect_to(root_url) unless @user == current_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
    redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "OVSAC"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    user == current_user
  end

  #Returns the current logged-in user (if any)
  def current_user
    #if @current_user doesn't exist, run the alternate statement and fetch it.
    @current_user = @current_user ||= User.find_by(id: session[:user_id])
  end

  #Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  #Redirects to stored location (or to the default).
  #Notes: Same as session facility we used for logging users in
  # uses the request object (via request.original_url) to get the URL of the requested page
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  #Stores the URL trying to be accessed.
  #Notes: the store_location method puts the requested URL in the sessions variable under the key
  #:forwarding URL if a user, say, submits a form when not logged in

  #if a user is not logged in, and clicks submit a form. (i.e. the user deleted session cookies by hand)
  #before submitting. the resulting redirect would issue a GET request to the URL expecitng POST, PATCH
  #DELETE, thereby causing an error. Including if request.get? prevents this from happening.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar for the user given.
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; <%= link_to "Chaos Design", '#', id:"contact_icon"%>
  </small>
  <nav>
    <ul>
    <!-- facebook link here -->

  </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="example3">
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar3">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%= image_tag("logo.png",alt:"ovsacLogo") %>
        </a>
      </div>
      <div id="navbar3" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to("Home", root_path)%></li>
          <li><%= link_to("Our Story", ourStory_path)%></li>
          <li><%= link_to("Who are we",whoarewe_path)%></li>
          <li><%= link_to("Events",clubEvents_path)%></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <% #If user is logged in then show the "Users Label"  %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, :method => :delete %>
                </li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to(signup_path) do %> <span class="glyphicon glyphicon-user"></span> Register<% end %></li>
              <li><%= link_to (login_path) do %> <span class="glyphicon glyphicon-user"></span> Log in<% end %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/header' %>
  </div class ="container">

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>

  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class ="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <%= @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "Our Story")%>
<h1>Our Story</h1>
<p>Coming soon...</p>
<%= image_tag("large_logo.png", height: 400, width: "auto") %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
<h1>Club Members</h1>
<p>Our Members profile page... coming soon</p>

app/views/static_pages/events.html.erb
<% provide(:title, "Contact")%>
<h1>Upcoming Club Events</h1>
</br>
<p><strong>September 18 - 22: SU Club Weeks</strong></p>
<p><strong>Where:</strong> MacEwan Student Centre North and South Courtyards</p>
<p><strong>When:</strong> 9:00am - 5:00pm</p>
<p><strong>What:</strong> Club information session + meet and greet</p>
<p><strong>Who:</strong> Anyone welcome!</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help Page</h1>
<p>Get help with the OVSAC web application</p>
<p>Lead Website developer: Justin Berry: jdberry@ucalgary.ca</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Ovarian Cancer</h1>
  <h2>Student Action Club</h2>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "DELETE MEMBER", user, method: :delete,
                    data: { confirm: "You sure?" } %>
      </br>
      <%= user.ucid %>
      </br>
      </br>
      Date Paid: <% user.date_paid %>
      </br>
      <%= puts "    " %>Paid? <%= user.is_paid %>
  <% end %>
  </br>
  <!-- non admins visible -->
  <%= puts "    " %>Major: <%= user.major %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your profile</h1>
<div class = "row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label(:name,'Full Name', class:"inLineLabel") %>
        <%= f.text_field(:name, class: 'form-control') %>

        <%= f.label(:email, 'Email', class:"inLineLabel") %>
        <%= f.text_field(:email, class: 'form-control') %>

        <%= f.label(:ucid, 'UCID (UofC students only)',class:"inLineLabel") %>
        <%= f.text_field(:ucid, class: 'form-control') %>

        <%= f.label(:major, 'Major',class:"inLineLabel") %>
        <%= f.text_field(:major, class: 'form-control') %>

        <%= f.label(:password,'Password (minimum length: 6)',class:"inLineLabel") %>
        <%= f.password_field(:password, class:'form-control') %>

        <%= f.label(:password_confirmation,'Password Confirmation:',class:"inLineLabel") %>
        <%= f.password_field(:password_confirmation, class: 'form-control') %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All Members</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Become a member of OVSAC!</h1>
<h2>$5 yearly membership fee applies</h2>
<div class = "row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label(:name,'*Full Name', class:"inLineLabel") %>
      <%= f.text_field(:name, class: 'form-control') %>

      <%= f.label(:email, '*Email', class:"inLineLabel") %>
      <%= f.text_field(:email, class: 'form-control') %>

        <%= f.label(:ucid, 'UCID (UofC students only)',class:"inLineLabel") %>
        <%= f.text_field(:ucid, class: 'form-control') %>

        <%= f.label(:major, 'Major (Students only)', class:"inLineLabel") %>
        <%= f.text_field(:major, class: 'form-control') %>

        <%= f.label(:password,'*Password (minimum length: 6)',class:"inLineLabel") %>
        <%= f.password_field(:password, class:'form-control') %>

        <%= f.label(:password_confirmation,'*Password Confirmation:',class:"inLineLabel") %>
        <%= f.password_field(:password_confirmation, class: 'form-control') %>

        <%= f.submit "Create membership", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "row">
  <aside class = "col-md-4">
    <section class = "user_info">
      <h1>
      <%= gravatar_for(@user) %>
      <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>